baseURL = "https://positionrelative.me/"
languageCode = "en-us"
title = "position:relative™"
enableGitInfo = true

[params]
  description = "The digital home of Renato de Leão, digital designer and front-end developer"